baseURL = 'https://jogsdevs.github.io/'
title = 'CodeCraft'
languageCode = 'id'

[pagination] 
  paperSize= 6

ignoreErrors = ["error-remote-getjson"]
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
toc = true

[markup]
[markup.highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = false
  hl_Lines = ''
  hl_inline = false
  lineAnchors = ''
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = 'monokai'
  tabWidth = 4
  wrapperClass = 'highlight'

[markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true

[outputs]
home = ["HTML", "JSON"]
section = ["HTML", "RSS"]
software = ["HTML"]  # Format khusus

[mediaTypes]
[mediaTypes."text/html"]
suffixes = ["html"]

[params]
  enableMediumZoom = true
  searchTypes = ["tutorial", "slug", "kategori"]
  teraboxBase = "https://terabox.com/s/"
  description = "Website resmi Jogja Devs, komunitas dan layanan developer Jogja."
  keywords = "jogja, devs, komunitas, developer, jasa, website, teknologi"
  author = "JogsDevs Team"
