baseURL = 'https://jogsdevs.github.io/'
title = 'CodeCraft'
languageCode = 'id'

[pagination] 
  paperSize= 6

[markup]
  [markup.highlight]
    style = "monokai"
    noClasses = false
    lineNos = true

[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true

[outputs]
home = ["HTML", "JSON"]

[params]
  searchTypes = ["tutorial", "slug", "kategori"]
  description = "Website resmi Jogja Devs, komunitas dan layanan developer Jogja."
  keywords = "jogja, devs, komunitas, developer, jasa, website, teknologi"
  author = "JogsDevs Team"
